// Mocks generated by Mockito 5.0.17 from annotations
// in tdd_flutter/test/funcionalidades/usuarios/dominio/casos_uso/obter_usario_casouso_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_flutter/funcionalidades/usuarios/dominio/entidades/usuario_entidade.dart'
    as _i6;
import 'package:tdd_flutter/funcionalidades/usuarios/dominio/repositorios/usuario_repositorio.dart'
    as _i2;
import 'package:tdd_flutter/nucleo/tratamento_erros/falhas.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UsuarioRepositorio].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioRepositorio extends _i1.Mock
    implements _i2.UsuarioRepositorio {
  MockUsuarioRepositorio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Falha, _i6.UsuarioEntidade>>? obterUsuarioCasoUso(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#obterUsuarioCasoUso, [id]))
          as _i3.Future<_i4.Either<_i5.Falha, _i6.UsuarioEntidade>>?);
}
