// Mocks generated by Mockito 5.0.17 from annotations
// in tdd_flutter/test/funcionalidades/usuarios/dados/repositorios_dados/usuario_repositorio_implementacao_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_flutter/funcionalidades/usuarios/dados/fontes_dados/api/usuario_api_fonte_dados.dart'
    as _i3;
import 'package:tdd_flutter/funcionalidades/usuarios/dados/fontes_dados/local/usuario_local_fonte_dados.dart'
    as _i5;
import 'package:tdd_flutter/funcionalidades/usuarios/dados/modelos/usuario_modelo.dart'
    as _i2;
import 'package:tdd_flutter/nucleo/plataforma/informacao_rede.dart' as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUsuarioModelo_0 extends _i1.Fake implements _i2.UsuarioModelo {}

/// A class which mocks [UsuarioApiFonteDados].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioApiFonteDados extends _i1.Mock
    implements _i3.UsuarioApiFonteDados {
  MockUsuarioApiFonteDados() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UsuarioModelo>? obterUsuarioCasoUso(int? id) =>
      (super.noSuchMethod(Invocation.method(#obterUsuarioCasoUso, [id]))
          as _i4.Future<_i2.UsuarioModelo>?);
}

/// A class which mocks [UsuarioLocalFonteDados].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsuarioLocalFonteDados extends _i1.Mock
    implements _i5.UsuarioLocalFonteDados {
  MockUsuarioLocalFonteDados() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UsuarioModelo> obterUltimoUsuario() => (super.noSuchMethod(
          Invocation.method(#obterUltimoUsuario, []),
          returnValue: Future<_i2.UsuarioModelo>.value(_FakeUsuarioModelo_0()))
      as _i4.Future<_i2.UsuarioModelo>);
  @override
  _i4.Future<void> cacheUsuario(_i2.UsuarioModelo? usuarioDoCache) =>
      (super.noSuchMethod(Invocation.method(#cacheUsuario, [usuarioDoCache]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [InformacaoRede].
///
/// See the documentation for Mockito's code generation for more information.
class MockInformacaoRede extends _i1.Mock implements _i6.InformacaoRede {
  MockInformacaoRede() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get estaConectado =>
      (super.noSuchMethod(Invocation.getter(#estaConectado),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
